export const COMMENTS_LOADING = "COMMENTS_LOADING";
export const COMMENTS_SUCCESS = "COMMENTS_SUCCESS";
export const COMMENTS_STOP = "COMMENTS_STOP";
export const COMMENTS_FAIL = "COMMENTS_FAIL";
export const COMMENTS_DELETE = "COMMENTS_DELETE";
export const COMMENTS_UPDATE = "COMMENTS_UPDATE";
